services:
  - type: worker
    name: discord-music-bot
    env: node
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false